import altair as alt
import pandas as pd
import argparse
import os

parser = argparse.ArgumentParser(description='Generate gantt plot for gaze from files generated by headPgaze.py.')
parser.add_argument('--basefilename', type=str, required=True, help='Filename of the bagfile')
parser.add_argument("-d", "--distancetype", default='cosine_distance', 
    help='type of distance to use (euclidien_distance, cosine_distance)')
args = parser.parse_args()
print(args.basefilename)


out_file = os.path.splitext(os.path.basename(args.basefilename))[0].split('_')[0]
print(out_file)


objects_file = os.path.join('gaze', out_file, args.distancetype,'objects.csv')
print(objects_file)
audio_file = os.path.join('gaze', out_file, args.distancetype,'audio.csv')
print(audio_file)

audio_csv = pd.read_csv(audio_file)
audio_list = []
df_audio = []
for index, frame in audio_csv.iterrows():
    audio_list.append(frame)
for i in range(len(audio_list)):
    transcript = audio_list[i]['transcript']
    start = audio_list[i]['start_timestamp']
    end =  audio_list[i]['end_timestamp']
    df_audio.append(
        {"Transcript":transcript ,"start":start, "end":end}
    )
source_audio = pd.DataFrame(df_audio)
chart_audio = alt.Chart(source_audio).mark_bar().encode(
    x = alt.X('start',
        scale=alt.Scale(zero=False)
    ),
    x2='end',
    y='Transcript',
).properties(
    width=1200,
    height=300
)

obj_csv = pd.read_csv(objects_file)
obj_list = []
df_obj = []
for index, frame in obj_csv.iterrows():
    obj_list.append(frame)
for i in range(len(obj_list)-1):
    obj_name = str(obj_list[i]['object'])#[9:].split('_')[0]
    print(obj_name)
    start = obj_list[i]['timestamp']
    end =  obj_list[i+1]['timestamp']
    df_obj.append(
        #{"Objects":obj_name.lower(), "start":start, "end":end}
        {"Objects":obj_name, "start":start, "end":end}
    )
source_obj = pd.DataFrame(df_obj)
chart_obj = alt.Chart(source_obj).mark_bar().encode(
    x = alt.X('start',
        scale=alt.Scale(zero=False)
    ),
    x2='end',
    y='Objects',
    color=alt.Color('Objects', scale=alt.Scale(scheme='dark2'))
).properties(
    width=1200,
    height=300
)



(chart_audio+chart_obj).save('gaze/'+out_file+'_gaze.html')
#chart_obj.save('gaze/'+out_file+'_gaze.html')